language: node_js

sudo: required

matrix:
  include:
    - os: osx
      node_js: 10
      env:
        - OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=4.1.2
    - os: linux
      node_js: 10
      env:
        - OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION=4.1.2

before_install:
  - "./setup_${TRAVIS_OS_NAME}.sh"
install:
  - npm install
  - npm test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - npm whoami
  - bsdtar -czf opencv-build.tar -h -C .. -T "package_${TRAVIS_OS_NAME}.txt"

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish opencv-build.tar
  on:
    tags: true
